### ISSUE TITLE
非常抱歉打扰，请问是否有百度网盘链接

### ISSUE THREAD

**Issue by WangWenda98** [snail-radar/snail-radar.github.io#2]
十分感谢作者优秀的工作，非常抱歉打扰，请问是否有百度网盘链接，Onedrive大文件下载会失败。

**Comment by JzHuai0108** [comment]
我在看百度网盘的事情。OneDrive下载大文件建议用OneDrive桌面安装版，进行同步/下载，这样稳健许多，而且不需要VPN。我测试感觉是这样的。

**Comment by WangWenda98** [comment]
好的，再次感谢您优秀的工作

**Comment by JzHuai0108** [comment]
用Onedrive桌面版app下载这些文件，
首先，把shared folder添加到你的onedrive account, 在网页上有一个按钮Add to my onedrive,
提示：添加shared folder不会增加你的onedrive空间消耗哈。
其次，用onedrive app下载你的账户中的这些文件，同步到本地。
基本上是这个操作流程，如果有问题，请贴图哈。

**Comment by MichaelSun1001** [comment]
作者们你们好，十分感谢作者们优秀的工作，我也是和上面那位同志一样的问题，后期能否发一下百度网盘链接，Onedrive大文件下载会失败，我尝试了很多方法，依旧会失败。
再次感谢作者们的优秀工作！！！！

**Comment by JzHuai0108** [comment]
好的，我在上传百度网盘了。估计两三天可以搞定了。百度网盘连接是
链接: https://pan.baidu.com/s/1wLjt2fIn5EDescEgf3D7gQ 提取码: 3141
上传完成后，我会更新一下这个repo的README。

PS: 我们有试过onedrive app，在有VPN的情况下，下载大文件30GB，还没发现问题，我们的网络速度也一般。无论如何，我先做好百度网盘。

**Comment by WangWenda98** [comment]
好的，十分感谢您&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "JzHuai0108"; 
Date: 2024年8月8日(星期四) 上午8:27
To: "snail-radar/snail-radar.github.io"; 
Cc: "Wenda"; "Author"; 
Subject: Re: [snail-radar/snail-radar.github.io] 非常抱歉打扰，请问是否有百度网盘链接 (Issue #2)

&nbsp;


 
好的，我在上传百度网盘了。估计两三天可以搞定了。百度网盘连接是
 链接: https://pan.baidu.com/s/1wLjt2fIn5EDescEgf3D7gQ 提取码: 3141
 上传完成后，我会更新一下这个repo的README。
 
PS: 我们有试过onedrive app，在有VPN的情况下，下载大文件30GB，还没发现问题，我们的网络速度也一般。无论如何，我先做好百度网盘。

**Comment by MichaelSun1001** [comment]
> 好的，我在上传百度网盘了。估计两三天可以搞定了。百度网盘连接是 链接: [pan.baidu.com/s/1wLjt2fIn5EDescEgf3D7gQ](https://pan.baidu.com/s/1wLjt2fIn5EDescEgf3D7gQ) 提取码: 3141 上传完成后，我会更新一下这个repo的README。
> 
> PS: 我们有试过onedrive app，在有VPN的情况下，下载大文件30GB，还没发现问题，我们的网络速度也一般。无论如何，我先做好百度网盘。

十分感谢您！！！！

**Comment by JzHuai0108** [comment]
The baidu netdisk benchmark dataset mirror is ready at https://pan.baidu.com/s/1wLjt2fIn5EDescEgf3D7gQ code: 3141

**Comment by MichaelSun1001** [comment]
> The baidu netdisk benchmark dataset mirror is ready at [pan.baidu.com/s/1wLjt2fIn5EDescEgf3D7gQ](https://pan.baidu.com/s/1wLjt2fIn5EDescEgf3D7gQ) code: 3141

thank you so much! ，thanks for you work!
