### ISSUE TITLE
请问ars548毫米波雷达的数据如何录制为pointcloud2格式

### ISSUE THREAD

**Issue by 3106171885** [snail-radar/snail-radar.github.io#3]
作者你好，抱歉打扰，我在尝试录制自己的数据集的时候，发现ars548雷达录制出的数据不尽人意，请问是否有这方面的资料或者教程，网上查找了一些都是零零散散的，非常感谢！！

**Comment by JzHuai0108** [comment]
我们用的wireshark录的UDP packets，然后用Python解析的UDP packets，再转成的ROS pointcloud2. 在录制的时候没有用ROS，因为你知道的，直接录ROS问题很多。录了坏的数据，后期没办法补救了。
有人已经开源了ARS548 解析办法：https://github.com/robotics-upo/ars548_ros

**Comment by 3106171885** [comment]
感谢作者回复，我去试一下，非常感谢！！

**Comment by wangchuanhao1231** [comment]
> 感谢作者回复，我去试一下，非常感谢！！



> 感谢作者回复，我去试一下，非常感谢！！

您好，我最近也想自己用ars548采集数据，遇到了一些问题，可以给个联系方式，向您请教吗

**Comment by JzHuai0108** [comment]
我一直关注github issue的动向哈，我尽早回复的。如果有问题发到这里来吧，这样也可能帮助到别人。
