### ISSUE TITLE
548 pointcloud intensity

### ISSUE THREAD

**Issue by MichaelSun1001** [snail-radar/snail-radar.github.io#4]
作者您好，感谢您的工作和开源！据我所知，548的点云只有RCS信息，请问数据集里面的intensity代表着RCS吗？
再次感谢您的工作！！！

**Comment by JzHuai0108** [comment]
Exactly. From the ars548 doc, it is "detection RCS". 我感觉这个应该是比较纯粹的RCS, 即[这里的\sigma](https://en.wikipedia.org/wiki/Radar_cross_section).

**Comment by MichaelSun1001** [comment]
> 完全。从 ars548 文档中，它是“检测 RCS”。我感觉这个应该是比较纯粹的RCS， 即[这里的\sigma](https://en.wikipedia.org/wiki/Radar_cross_section).

作者您好，感谢您的工作！！！我也采集了一些数据，我的rcs单位是db/m²，得到的很多都是负值，可是我看到snail-radar 里面的 data4.bag里面的intensity都是很大的值，也都是正值，请问这是为什么呢？
下面给出我采集的数据截图和data4.bag里面的截图
![image](https://github.com/user-attachments/assets/47353eaf-e618-4bf4-b5f7-c6b19bcbf1da)
![image](https://github.com/user-attachments/assets/1a771c4e-65fb-42e4-8241-4b1a1bbc1d5f)

**Comment by JzHuai0108** [comment]
RCS的单位应该是m^2, 你的数据的单位是db/m^2, 这应该不是同一个物理量，所以会有负值吧。请问你们用的是什么型号的毫米波雷达？

**Comment by MichaelSun1001** [comment]
> RCS的单位应该是m^2, 你的数据的单位是db/m^2, 这应该不是同一个物理量，所以会有负值吧。请问你们用的是什么型号的毫米波雷达？

作者您好，我是用的是ARS548，我在data4.bag中的截图也是548的话题/ars548，可是我发现您的数据这样基本上都保持在一百多左右，感觉有点问题，我转换成m²也和您的数据相差太多，而且您的数据基本上都是110-200左右的，感觉很奇怪，这个数据很不正常。

**Comment by JzHuai0108** [comment]
1. 我去翻了一下ars548 udp pcapng file,和我们用的数据预处理的脚本，原来我们在处理的时候 RCS <- RCS + 128. 所以我们的值减去128和你们的就一致了。这让我想起了很久之前的一个[问题](https://github.com/thucyw/mmWave-Radar-Relocalization/issues/2). 我当时也奇怪为啥那里的RCS值变化幅度很小，大致在0 - 16之间。
3. 还有一个问题是为啥你们rcs单位是db/m²？我预期的是m^2. 实话说，我对RCS的了解止于书本。

**Comment by JzHuai0108** [comment]
Hopefully this concludes our discussion.
1. There was a mistake in our data conversion tool. To get the correct RCS value, we should subtract 128 from the current RCS values in our dataset.
2. The RCS value unit is db m^2.  So RCS(m^2) = 10^{RCS(db m^2) / 10}.

**Comment by MichaelSun1001** [comment]
> Hopefully this concludes our discussion.
> 
> 1. There was a mistake in our data conversion tool. To get the correct RCS value, we should subtract 128 from the current RCS values in our dataset.
> 2. The RCS value unit is db m^2.  So RCS(m^2) = 10^{RCS(db m^2) / 10}.

Yes, I mixed up the unit, I have fully understood, thank you for your work！！！
